version: "3"

services:
  calendar:
    build:
      context: ../.
      dockerfile: build/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "50051:50051"
    networks:
     - calendar-network
  calendar_scheduler:
    build:
      context: ../.
      dockerfile: build/DockerfileScheduler
    depends_on:
      - db
      - broker
    networks:
     - calendar-network
  calendar_sender:
    build:
      context: ../.
      dockerfile: build/DockerfileSender
    depends_on:
      - broker
    networks:
     - calendar-network
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: calendar
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../data:/var/lib/postgresql/data
    networks:
      - calendar-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - calendar-network

  broker:
    image: wurstmeister/kafka
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS="Calendar:1:0"
    networks:
      - calendar-network
    volumes:
      - ../data/mq:/var/lib/confluent-control-center
networks:
  calendar-network: