version: "3"

services:
  calendar:
    ports:
      - "8888:8080"
      - "50051:50051"

  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: calendar
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../data:/var/lib/postgresql/data

  zookeeper:
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  broker:
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS:  "PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CREATE_TOPICS: "Calendar:1:0,Notification:1:0"
    volumes:
      - ../data/mq:/var/lib/confluent-control-center