version: "3"

services:
  calendar:
    restart: on-failure
    build:
      context: ../.
      dockerfile: build/Dockerfile
      args:
        ORIGINAL_CONFIG_FILE: $APP_CONFIG_FILE
    env_file:
      - .env
    depends_on:
      - db
    networks:
     - calendar-network

  calendar_scheduler:
    restart: on-failure
    build:
      context: ../.
      dockerfile: build/DockerfileScheduler
      args:
        ORIGINAL_CONFIG_FILE: $SCHEDULER_CONFIG_FILE
    env_file:
      - .env
    depends_on:
      - db
      - broker
    networks:
     - calendar-network

  calendar_sender:
    restart: on-failure
    build:
      context: ../.
      dockerfile: build/DockerfileSender
      args:
        ORIGINAL_CONFIG_FILE: $SENDER_CONFIG_FILE
    env_file:
      - .env
    depends_on:
      - broker
    networks:
     - calendar-network
  db:
    image: postgres:14.5
    networks:
      - calendar-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - calendar-network

  broker:
    image: wurstmeister/kafka
    container_name: broker
    depends_on:
      - zookeeper
    networks:
      - calendar-network
networks:
  calendar-network: