[logger]
level = "ERROR"

[sql]
driverName = "postgres"
dataSourceName = "user=admin dbname=calendar password=admin host=db port=5432 sslmode=disable"
migrationsDir = "./migrations"

[scheduler]
timeout = "1m"

[cleaner]
cleanAfter = "-4320h"

[kafka]
topic = "calendar"
hosts = [
    "broker:9092"
]


