[logger]
level = "ERROR"

[storage]
type = "in_memory"

[http]
host = "localhost"
grpcPort = "50051"
type="tcp"
gatewayPort="8080"

[sql]
driverName = "postgres"
dataSourceName = "user=admin dbname=calendar password=admin host=172.17.0.1 port=5432 sslmode=disable"
migrationsDir = "./migrations"

